from __future__ import annotations


CANONICAL_GRAMMAR_V1_SKILLS = (
    "grammar.present_simple.affirmative",
    "grammar.present_simple.third_person_s",
    "grammar.present_simple.negative",
    "grammar.present_simple.questions",
    "grammar.present_continuous.form",
    "grammar.present_continuous.current_action",
    "grammar.present_continuous.temporary_situation",
    "grammar.past_simple.regular_verbs",
    "grammar.past_simple.irregular_verbs",
    "grammar.past_simple.negative",
    "grammar.past_simple.questions",
    "grammar.past_simple.finished_past",
    "grammar.past_continuous.form",
    "grammar.past_continuous.background_action",
    "grammar.past_continuous.interrupted_action",
    "grammar.present_perfect.form",
    "grammar.present_perfect.past_participle",
    "grammar.present_perfect.experience",
    "grammar.present_perfect.unfinished_time",
    "grammar.present_perfect.recent_result",
    "grammar.present_perfect.since_for",
    "grammar.future.will_prediction",
    "grammar.future.will_spontaneous_decision",
    "grammar.future.will_offer_promise",
    "grammar.modality.can_ability",
    "grammar.modality.can_permission",
    "grammar.modality.could_past_ability",
    "grammar.modality.must_obligation",
    "grammar.modality.should_advice",
    "grammar.modality.must_vs_have_to",
    "grammar.articles.a_an",
    "grammar.articles.the_specific_reference",
    "grammar.articles.zero_article",
    "grammar.articles.first_vs_subsequent_mention",
    "grammar.articles.generic_reference",
    "grammar.conditionals.zero",
    "grammar.conditionals.first",
    "grammar.conditionals.second",
    "grammar.conditionals.first_vs_second",
    "grammar.passive.be_past_participle",
    "grammar.passive.present_simple",
    "grammar.passive.past_simple",
    "grammar.passive.agent_by",
)

CANONICAL_GRAMMAR_V1_SKILL_SET = frozenset(CANONICAL_GRAMMAR_V1_SKILLS)
