export const designTokens = {
  color: {
    bgPage: "#f6f8fb",
    bgSurface: "#ffffff",
    bgSidebar: "#0f172a",
    bgNavActive: "#e8efff",
    actionPrimaryFill: "#2454a6",
    actionPrimarySoft: "#e8efff",
    actionPrimaryDark: "#162f63",
    actionPrimaryMid: "#4d72bd",
    statusSuccess: "#147447",
    statusSuccessSoft: "#e7f6ee",
    statusWarningSoft: "#fff7e6",
    statusErrorSoft: "#fff0ed",
    statusInfoSoft: "#eef4ff",
    textStrong: "#162033",
    textMuted: "#667085",
    borderSubtle: "#d9e0ea",
  },
  radius: {
    control: 8,
    compact: 10,
    card: 12,
    hero: 20,
    pill: 999,
  },
  space: {
    twoXs: 4,
    xs: 8,
    compact: 10,
    sm: 12,
    cardInner: 14,
    md: 16,
    lg: 18,
    section: 22,
    xl: 24,
    twoXl: 32,
    page: 34,
  },
} as const;
